# Generated by Django 4.2.4 on 2023-09-22 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_usapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 13, 36, 52, 509084)),
        ),
    ]
